### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by atalebagha** [quran/quran.com-api-node#1]
Salaam,

I would love to contribute to this.  I'm rusty with ROR but I'm good with Node.js.  I've noticed this repo has not had any activity yet.

**Comment by mmahalwy** [comment]
Salam

Yes, I left this as a trial for API since I thought API would be faster if served by node. That being said, the content hardly changes and made sense to leverage caching than rewritingeverything in node. 
Going to deprecate this :(

**Comment by ahmedre** [comment]
@atalebagha if you're good with Node, we'd welcome your help on quran/quran.com-frontend and quran/audio.quran.com

**Comment by mmahalwy** [comment]
Thanks @ahmedre - github on mobile is sad :(

**Comment by atalebagha** [comment]
What if you plan on adding more services like hifth tracking, more content (such as tafasir), notes, bookmarks to help tullaab al-3ilm.

**Comment by mmahalwy** [comment]
We are working on a user auth with bookmarks, tracking, etc. here: https://github.com/quran/onequran
